@startuml
skinparam dpi 300
skinparam linetype ortho
skinparam ParticipantPadding 50
skinparam roundcorner 10
skinparam classFontSize 15


entity "Loan" as loan {
    loan_id
    account_id
    contract_number
    start_date
    end_date
    body_amount
    currency
    status
    IBAN
}

entity "Client" as client {
    client_id
    account_id
    phone_number
    email
    first_name
    last_name
    RNTC
}

entity "Account" as account{
    account_id
    client_id
    IBAN
}

entity "Transaction" as transaction{
    transaction_id
    account_id
    transaction_type
    status
    date
    amount
    currency
    IBAN
}

entity "PaymentInvoice" as invoice {
    payment_invoice_id
    loan_id
    body_amount
    fee
    penalty
    currency
    due_date
    status
}

client ||-o{ account
account ||-o{ transaction
loan }o--|| account
loan ||-o{ invoice


@enduml